name: create github release
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: create github release
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: create github release if required
      run: |
        python scripts/create_github_release.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
